services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: booking
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - booking-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - booking-network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  nginx-lb:
    build: ./nginx-lb
    container_name: nginx-lb
    ports:
      - "80:80"
    depends_on:
      - api-gateway-1
      - api-gateway-2
      - frontend
    networks:
      - booking-network

  api-gateway-1:
    build: ./api-gateway
    container_name: api-gateway-1
    restart: always
    ports:
      - "8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - ALLOWED_ORIGINS=http://localhost
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/booking?authSource=admin
      - DATABASE_NAME=Booking
      - JWT_SECRET_KEY=YRMCKrygcXtx1bVpEMcBKIK9LxX8aDUTUQy2XyuLRCbnoPOhxUeIPqIQW01UfC6QgEKETKf2rM9UQnc4FkRSxA
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - booking-network

  api-gateway-2:
    build: ./api-gateway
    container_name: api-gateway-2
    restart: always
    ports:
      - "8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - ALLOWED_ORIGINS=http://localhost
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/booking?authSource=admin
      - DATABASE_NAME=Booking
      - JWT_SECRET_KEY=YRMCKrygcXtx1bVpEMcBKIK9LxX8aDUTUQy2XyuLRCbnoPOhxUeIPqIQW01UfC6QgEKETKf2rM9UQnc4FkRSxA
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - booking-network

  authentication-service:
    build: ./authentication-service
    container_name: authentication-service
    restart: always
    ports:
      - "8086:8086"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/booking?authSource=admin
      - DATABASE_NAME=Booking
      - MAIL_REGISTER_CONFIRMATION_LINK=http://localhost/valider-email/
      - MAIL_PASSWORD=cnbv zhqy yfej acqm
      - MAIL_MODIFIED_USERNAME=EventHub
      - APP_EMAIL=4webd.booking.event.hub@gmail.com
      - JWT_SECRET_KEY=YRMCKrygcXtx1bVpEMcBKIK9LxX8aDUTUQy2XyuLRCbnoPOhxUeIPqIQW01UfC6QgEKETKf2rM9UQnc4FkRSxA
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks:
      - booking-network

  event-service:
    build: ./event-service
    container_name: event-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/booking?authSource=admin
      - DATABASE_NAME=Booking
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - booking-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: always
    ports:
      - "8082:8082"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/booking?authSource=admin
      - DATABASE_NAME=Booking
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - booking-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    restart: always
    ports:
      - "8083:8083"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/booking?authSource=admin
      - DATABASE_NAME=Booking
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - booking-network

  ticket-service:
    build: ./ticket-service
    container_name: ticket-service
    restart: always
    ports:
      - "8084:8084"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/booking?authSource=admin
      - DATABASE_NAME=Booking
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - booking-network

  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    ports:
      - "8085:8085"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/booking?authSource=admin
      - DATABASE_NAME=Booking
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - booking-network

  frontend:
    build: ./booking-frontend
    container_name: booking-frontend
    restart: always
    environment:
      - API_BASE_URL=http://localhost/api
    networks:
      - booking-network

networks:
  booking-network:
    driver: bridge

volumes:
  mongodb_data:
  rabbitmq_data: